 "use client";
import {useState} from "react";
import {Lock, Sparkles, Image, Video, FolderOpen, UserRound, Settings, LogOut, Menu, X} from "lucide-react";

const items=[["Studio",Sparkles],["Images",Image],["Videos",Video],["Library",FolderOpen],["Characters",UserRound]] as const;

export default function Home(){
 const [logged,setLogged]=useState(false),[pass,setPass]=useState(""),[error,setError]=useState(""),[tab,setTab]=useState("Studio"),[mobile,setMobile]=useState(false);
 if(!logged)return <main className="login"><div className="loginCard"><div className="logo">X</div><h1>Your private studio</h1><p>Personal AI workspace. Nothing public.</p><div className="input"><Lock size={18}/><input type="password" placeholder="Private password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==="Enter"&&(pass?setLogged(true):setError("Enter a password"))}/></div><button onClick={()=>pass?setLogged(true):setError("Enter a password")}><Lock size={17}/> Enter studio</button>{error&&<small>{error}</small>}<span className="hint">This starter uses a local session. Add real auth before publishing sensitive content.</span></div></main>;
 return <div className="app"><aside className={mobile?"open":""}><div className="brand"><div className="logo small">X</div><b>XoticAI</b><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{items.map(([name,Icon])=><button className={tab===name?"active":""} key={name} onClick={()=>{setTab(name);setMobile(false)}}><Icon size={19}/>{name}</button>)}</nav><div className="bottom"><button><Settings size={19}/>Settings</button><button onClick={()=>setLogged(false)}><LogOut size={19}/>Lock studio</button></div></aside><div className="main"><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div><span>PRIVATE STUDIO</span><h2>{tab}</h2></div><div className="avatar">P</div></header>{tab==="Studio"?<Studio/>:<Section title={tab}/>}</div></div>
}
function Studio(){const [prompt,setPrompt]=useState("");const [type,setType]=useState("Image");const [done,setDone]=useState(false);return <section className="content"><div className="hero"><div><div className="pill"><Sparkles size={15}/> PERSONAL MODE</div><h1>Create without the clutter.</h1><p>A simple private workspace for your own AI images and videos.</p></div><div className="orb">✦</div></div><div className="generator"><div className="switch"><button className={type==="Image"?"on":""} onClick={()=>setType("Image")}>Image</button><button className={type==="Video"?"on":""} onClick={()=>setType("Video")}>Video</button></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={`Describe what you want to create...`}/><div className="genbar"><span>Private • saved locally in this starter</span><button onClick={()=>setDone(true)} disabled={!prompt.trim()}><Sparkles size={17}/> Generate</button></div>{done&&<div className="result"><div className="placeholder">{type==="Image"?"IMAGE PREVIEW":"VIDEO PREVIEW"}</div><div><b>Demo generation ready</b><p>Connect an AI provider later to replace this preview with real generation.</p></div></div>}</div><div className="cards"><div><Image/><b>Images</b><span>Fast personal generations</span></div><div><Video/><b>Videos</b><span>Build short clips</span></div><div><FolderOpen/><b>Library</b><span>Keep your creations</span></div></div></section>}
function Section({title}:{title:string}){return <section className="content"><div className="empty"><div className="emptyIcon">{title==="Characters"?<UserRound/>:title==="Library"?<FolderOpen/>:title==="Videos"?<Video/>:<Image/>}</div><h1>{title}</h1><p>This private section is ready for your personal content.</p><button><Sparkles size={17}/> Open studio</button></div></section>}